### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by hrppl** [mountln/RRTN-old-film-restoration#1]
Great work, how did you process your dataset?

**Comment by mountln** [comment]
Sorry for the late reply.
You can find the code for data preprocessing in [VP_code/data/](https://github.com/mountln/RRTN-old-film-restoration/tree/main/VP_code/data). This part is almost the same as the approach used in the prior study, [Bringing Old Films Back to Life](http://raywzy.com/Old_Film/). You can refer to their paper as well.
